#pragma once

#define WHITE			FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE
#define BRIGHT_WHITE	FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define RED				FOREGROUND_RED
#define BRIGHT_RED		FOREGROUND_RED|FOREGROUND_INTENSITY
#define BLUE			FOREGROUND_BLUE
#define BRIGHT_BLUE		FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define GREEN			FOREGROUND_GREEN
#define BRIGHT_GREEN	FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define YELLOW			FOREGROUND_RED|FOREGROUND_GREEN
#define BRIGHT_YELLOW	FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define CYAN			FOREGROUND_BLUE|FOREGROUND_GREEN
#define BRIGHT_CYAN		FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define PURPLE			FOREGROUND_RED|FOREGROUND_BLUE
#define BRIGHT_PURPLE	FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY

#define BLANK_LINE "                                                                             \n"

enum class DemoMode
{
	Connecting,
	Moving
};
